[package]
name = "libr-os"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = "0.9.18"
lazy_static = { version = "1.4.0", "features" = ["spin_no_std"] }
spin = "0.9.0"
volatile = "0.2.6"
